export default  [
    {
        id:1,
        title:"首页",
        key:"/admin/home"
    },
    {
        id:2,
        title:"UI",
        key:"/admin/ui",
        children:[
            {
                id:3,

                title:"按钮",
                key:"/admin/ui/buttons",
            },
            {
                id:4,
                title:"加载中",
                key:"/admin/ui/loadings",
            },
            {
                id:5,
                title:"消息",
                key:"/admin/ui/messages",
            },
            {
                id:6,
                title:"弹窗",
                key:"/admin/ui/modals",
            },
            {
                id:7,
                title:"通知",
                key:"/admin/ui/notices",
            },
            {
                id:8,
                title:"表格",
                key:"/admin/ui/tables",
            },
            {
                id:9,
                title:"表单",
                key:"/admin/ui/forms",
            },
            {
                id:10,
                title:"tab切换",
                key:"/admin/ui/tabs",
            },
        ]
    },
    {
        id:11,
        title:"基础表单",
        key:"/admin/basetable/index"
    },
    {
        id:12,
        title:"基础图表",
        key:"/admin/baseechart/index"
    },
    {
        id:13,
        title:"视频",
        key:"/admin/video/index"
    },
    {
        id:14,
        title:"富文本",
        key:"/admin/richtext/index"
    },

]